### PR TITLE
const ALOOPER_PREPARE_ALLOW_NON_CALLBACKS

### PR DESCRIPTION
**Pull request by ratijas**
https://developer.android.com/ndk/reference/group/looper#group___looper_1gga4caf8d8f829279fba122163d961608a4a1fff26ab5859b0308b58a3f8d58ef1eb

### CODE REVIEW

**Comment by Nercury** [comment]
Made this const public in https://github.com/Nercury/android_looper-sys-rs/pull/2

**Comment by Nercury** [comment]
Sorry, I have removed your constant after a more careful review: https://github.com/Nercury/android_looper-sys-rs/pull/3

**Comment by ratijas** [comment]
LGTM :+1:

**Comment by ratijas** [comment]
btw, there supposed to be a difference between *-sys and non-sys crates where the former provides raw ffi declarations, and the latter wraps them into rust-specific types, enums and lifetimes; but i guess it does not matter much for such a relatively small codebase.

**Comment by Nercury** [comment]
I probably considered those enums "sufficiently raw" when I wrote this 2 years ago...

**Pull request merged**
